server:
  port: 8000 # 配置端口号
  context-path: /provider # 配置当前模块的context-path，即每个请求前都必须附加上这个路径
debug: true
spring:
  application:
    name: microservicecloud-provider   # 在使用eurake功能的时候非常重要，这个就是该服务的实例名，eurake可以通过该实例名获得这个服务的其中一个实例（服务端集群）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicecloud?serverTimezone=UTC # 数据库名称,暂时我这个版本不加serverTimezone会报一个错误
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                  # 数据库连接池的最小维持连接数
      initial-size: 5             # 初始化连接数
      max-total: 5                # 最大连接数
      max-wait-millis: 200       # 等待连接获取的最大超时时间

eureka:
  client:       # 当前微服务只是eureka的客户端
    service-url:
      # 单机使用
      defaultZone: http://eureka7000.com:7000/eureka
      ## eureka集群时使用
      # defaultZone: http://eureka7000.com:7000/eureka,http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 将当前微服务注册到指定的eureka服务端中

  instance:
      instance-id: microservicecloud-provider
      prefer-ip-address: true     #在eureka管理界面查看微服务路径可以显示IP地址

info:
  app-name: microservicecloud-provider
  copyright: ddf
  description: "微服务提供者"
logging:
  level: debug

